#!/bin/sh

set -e
set -o pipefail
set -o nounset

ip="${1}"

TARGET='armv7-unknown-linux-gnueabihf'

cross build --release --target "${TARGET}"

rsync -avz --include garage-door --include garage-speakers --exclude '*' "target/${TARGET}/release/" pi@"${ip}:/tmp/garage/"

ssh pi@"${ip}" sudo timedatectl set-timezone Europe/Vienna
echo 'garage' | ssh pi@"${ip}" sudo tee /etc/hostname

if ssh pi@"${ip}" ! [ -x "$(which shairport-sync)" ]; then
  ssh pi@"${ip}" < setup_shairport.sh
fi

ssh pi@"${ip}" sudo cp -f /tmp/garage/garage-speakers /usr/local/bin/garage-speakers
ssh pi@"${ip}" sudo cp -f /tmp/garage/garage-door /usr/local/bin/garage-door

cat <<CONFIG | ssh pi@"${ip}" sudo tee /etc/systemd/system/garage-door.service
[Unit]
Description=garage-door

[Service]
Type=simple
ExecStart=/usr/local/bin/garage-door
Restart=always

[Install]
WantedBy=multi-user.target
CONFIG

ssh pi@"${ip}" sudo systemctl enable garage-door
ssh pi@"${ip}" sudo systemctl restart garage-door
