#!/bin/sh

set -e
set -o pipefail
set -o nounset

ip="${1}"

TARGET='armv7-unknown-linux-gnueabihf'

cross build --release --target "${TARGET}"

rsync -avz --include garage --include garage-speakers --exclude '*' "target/${TARGET}/release/" pi@"${ip}:/tmp/garage/"

ssh pi@"${ip}" < setup_timezone.sh
ssh pi@"${ip}" < setup_hostname.sh
ssh pi@"${ip}" < setup_i2c.sh
ssh pi@"${ip}" < setup_watchdog.sh

if ssh pi@"${ip}" '! [ -f "$(which shairport-sync)" ]'; then
  ssh pi@"${ip}" < setup_shairport.sh
fi

if ssh pi@"${ip}" '! [ -f "$(which motion)" ]'; then
  ssh pi@"${ip}" < setup_camera.sh
fi


ssh pi@"${ip}" sudo mv -f /tmp/garage/garage-speakers /usr/local/bin/garage-speakers
ssh pi@"${ip}" sudo mv -f /tmp/garage/garage /usr/local/bin/garage

cat <<CONFIG | ssh pi@"${ip}" sudo tee /etc/systemd/system/garage.service
[Unit]
StartLimitAction=reboot
StartLimitIntervalSec=60
StartLimitBurst=10
Description=garage

[Service]
Type=simple
Environment=I2C_DEVICE=/dev/i2c-1
Environment=RUST_LOG=info
ExecStart=/usr/local/bin/garage
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
CONFIG

ssh pi@"${ip}" sudo systemctl enable garage
ssh pi@"${ip}" sudo systemctl restart garage
