#!/bin/bash

set -e
set -o pipefail
set -o nounset

ip="${1}"

shift

binary="${1}"

shift

rsync -avz ./ pi@"${ip}":garage/ --exclude target &&
ssh pi@"${ip}" -t "bash -l -c 'cd garage && cargo run --release --bin garage-'${binary}' -- ${@:-}'"
